### ISSUE TITLE
Have a look to my fork ? :)

### ISSUE THREAD

**Issue by tigerblue77** [ShaneMcC/docker-omsa#5]
And opened issues :)

**Comment by ShaneMcC** [comment]
Had a look, some comments:

- The reason I specify `:8.6` not `:latest` is so that (in theory!) dependabot can come along and poke the image up to date from time to time (otherwise it's fairly handsoff - it works so I don't need to touch it)
- Using minimal `RUN` commands in the docker image to reduce the number of layers
- Not sure of the need to rename the `run.sh` file or some of the changes (ie changing all the env var names etc)
- I have my own separate build server which handles the build rather than using actions, though perhaps could migrate to actions
