### ISSUE TITLE
Change base image to Ubuntu to have a smaller image ?

### ISSUE THREAD

**Issue by tigerblue77** [ShaneMcC/docker-omsa#6]

**Comment by ShaneMcC** [comment]
I specifically use a RHEL derivative because that is what Dell support in https://linux.dell.com/repo/hardware/dsu/bootstrap.cgi

Historically, Dell were not good at making deb-based versions of omsa available in a timely manor and released newer versions of OMSA only for CentOS with Debian support lagging some years behind. (This was my main driver for doing this in fact, as I upgraded some servers to Proxmox 6 which was Debian 6 based which they did not support and there was a lot of guides to making it somewhat (unreliably) work (eg: https://forum.proxmox.com/threads/dell-openmanage-on-proxmox-6-x.57932).)

See: https://linux.dell.com/repo/community/ubuntu/

> This is the Dell OpenManage repository for Ubuntu Server LTS and select Debian releases. It is NOT officially supported by Dell and is provided as an unofficial build for customers not able to use our officially supported builds of OMSA for RHEL and SLES.


These days it does seem like they do support debian/ubuntu more: https://linux.dell.com/repo/community/openmanage/ but I'd rather stick with RHEL for now as I've not tracked how often they update these.

**Comment by ShaneMcC** [comment]
Incidentally, I did look into switching to the `-minimal` almalinux base image, but this resulted in minimal savings overall (around 100mb - 1.14GB down to 1.09GB) and I don't know how (if at all) this may negatively impact the operation of OMSA.

Much of our image size is actually caused by OMSA itself:

```
$ docker history --no-trunc --format '{{printf "%10s" .Size}}\t{{.CreatedBy}}' shanemcc/docker-omsa:test | grep -v "[[:digit:]][kB|B]"
    6.07MB      RUN /bin/sh -c dnf clean all &&     rm -Rfv /usr/lib/systemd/system/autovt@.service /usr/lib/systemd/system/getty@.service /tmp/bootstrap.sh # buildkit
     985MB      RUN /bin/sh -c dnf -y install srvadmin-all # buildkit
    1.77MB      RUN /bin/sh -c cat /tmp/bootstrap.sh | bash # buildkit
    54.8MB      RUN /bin/sh -c ln -s /usr/bin/microdnf /usr/bin/dnf &&     dnf -y update &&     dnf -y install passwd procps kmod # buildkit
    93.7MB      /bin/sh -c #(nop) ADD file:173563d1538662ea5fdd4d535e8722eb5fa5f08467c68f5c51a2061d78ebd5f1 in /
```

**Comment by ShaneMcC** [comment]
(As part of upgrading to 9.1 in bfcab0daeed698f281ffa3133e953552d9359b04 I did also switch to using `-minimal` as well)
